server.port=8080

# Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/shmamsa_db?currentSchema=shmamsa
spring.datasource.username=shmamsa_user
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=shmamsa
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY

# JWT secret
jwt.secret=9fA7xQm2LZpR4kW8N3HcEJvS6YB5DUTGdM0eIoaFnC1XrQK
jwt.expiration-ms=86400000


# ===============================
# EMAIL OTP (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malakjackop26@gmail.com
spring.mail.password=gsui zxce hdhg rzaa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ? IMPORTANT: force From address (fixes can't determine local email address)
app.servant-secret-admin-email=malakjackop26@gmail.com
app.servant-secret-ttl-hours=24
spring.mail.default-encoding=UTF-8

# Servant registration secret (used by /api/auth/register-servant)
app.servant-register-secret=shmamsa@2026

# QR token secret (defaults to jwt.secret if not set)
qr.secret=QrSecret_ChangeMe_AtLeast_32_Chars_Long_1234567890

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Built-in DEVELOPER account (created automatically on startup)
app.dev.enabled=true
app.dev.username=developer
app.dev.password=developer@2026

# Disable OpenHTMLToPDF JUL logs
logging.level.com.openhtmltopdf=OFF
logging.level.com.openhtmltopdf.load=OFF
logging.level.com.openhtmltopdf.match=OFF
logging.level.com.openhtmltopdf.general=OFF
logging.level.com.openhtmltopdf.css-parse=OFF
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR
